spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: miniedu.app@gmail.com
    password: ENC(jgPzcvDk8C45j8SRkKCqW43dzVmhgR3t8rc+2Bw2xco=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
