spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-microservice?reWriteBatchedInserts=true
    username: postgres
    password: ${DB_PASSWORD}
    initialization-mode: always
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: miniedu.app@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
