spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-microservice?reWriteBatchedInserts=true
    username: postgres
    password: ${DB_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect