spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/user-microservice?reWriteBatchedInserts=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
